### ISSUE TITLE
Charmpp recipe lacks a Python/Cython dependency 

### ISSUE THREAD

**Issue by dipietrantonio** [PawseySC/pawsey-spack-config#131]
charmpp builds when spack is loaded with cray-python, but not when spack is loaded with python/3.9.15. This means our Python build lacks something (cython) that cray-python has got. It also means the recipe of charmpp lacks an explicit dependency on Python built with cython. We should fix this

**Comment by halfflat** [comment]
It turns out that the problem is a component `PythonCCS` that is built against the Python 2 API. With the `cray-python` module loaded, the charm++ configure script determines that Python headers/libs are unavailable, and disables internal Python support. With the `python/3.9.15` module load, the configure script is able to successfully compile and link a test program (that is Python 2 vs 3 agnostic), and consequently enables internal Python support; the build then fails because of API differences.

A more robust fix will be to remove the Python testing part of the configure script so that building PythonCCS is never attempted.
